version: '2.2'

services:

  elasticsearch:
    restart: always
    image: elasticsearch:6.4.1
    #volumes:
    #  - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    #  - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 15920:9200
      - 15930:9300
    network_mode: bridge
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    cpus: 2

  kibana:
    restart: always
    image: kibana:6.4.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 15601:5601
    network_mode: bridge
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    cpu_shares: 50
    cpus: 1

    #kfkbeat:
    #kfrestart: always
    #kfimage: reg-docker-dp.nqyong.com/zuji/kfkbeat:latest
    #kfvolumes:
    #kf  - ./kfkbeat/data:/usr/local/work/data:ro
    #kf  - ./kfkbeat/logs:/usr/local/work/logs
    #kfnetwork_mode: bridge
    #kfdepends_on:
    #kf  - elasticsearch
    #kflinks:
    #kf  - elasticsearch:elasticsearch
    #kfextra_hosts:
    #kf  - zookeeper:172.18.124.153
    #kf  - kafka1:172.18.124.150
    #kf  - kafka2:172.18.124.153
    #kfcpus: 1
